### PR TITLE
khairatAA created the pull request: The homepage_images folder was created to contain all images and logos

### PR DESCRIPTION
**Pull request by khairatAA**
## Description:
- Created the home page images folder which contains all the icons and images used in the figma file for the homepage. 

## Changes Made:
- Created homepage images folder
- Added files containing icons and images used in the homepage of the figma file

## Related Issue:
- Added files containing icons and images used in the homepage of the figma file

## Screenshots (if applicable):
- Attach screenshots, if applicable, to showcase the newly implemented feature or bug fix.

### CODE REVIEW

**Comment by khairatAA** [comment]
@ALX-SE-Algorithmia/code-reviewing-team 
Please kindly, check the PR created by khairatAA.
A homepage_images folder was created to contain all images and logos in the homepage on the figma design

**Comment by MartyOfMCA** [comment]
Hi @khairatAA, great job. I'd request some changes before we proceed with your PR.
Kindly follow the following:
* Images like the Algorithmia logo and the SVG files should be placed in a new directory called `shared`. 
* The other images specific to the homepage should be in a new directory named `home`.

Thank you!

**Comment by khairatAA** [comment]
According to the corrections made my the @ALX-SE-Algorithmia/code-reviewing-team,
I have made some modifications to the directory names as asked. Kindly review the changes made, Thanks.

**Comment by khairatAA** [comment]
Hy @ALX-SE-Algorithmia/code-reviewing-team, I have removed the readme file in the home directory as requested.

**Review by MartyOfMCA — APPROVED** [review]
Great work @khairatAA

**Comment by dohoudaniel** [comment]
Weldone @khairatAA.
Your PR shall be merged accordingly.
@MartyOfMCA Thank you for the review.

**Pull request merged**
