### PR TITLE
logo added

### PR DESCRIPTION
**Pull request by NanaAba08**
## Description: i added the company logo to the index.html file
- Explain the functionality or bug fix implemented in this pull request, including its purpose and significance.

## Changes Made:
- Provide a detailed overview of the code changes made to introduce this implementation, along with any relevant code snippets or files.

## Related Issue: issue #10 
- Fixes #[ISSUE_NUMBER]

## Screenshots (if applicable):
- Attach screenshots, if applicable, to showcase the newly implemented feature or bug fix.

### CODE REVIEW

**Comment by dohoudaniel** [comment]
Hi @NanaAba08.
Thank you for linking the logo to the website.
Your PR shall be merged.

**Comment by NanaAba08** [comment]
Thank you for your response.

**Comment by dohoudaniel** [comment]
Hi @NanaAba08.
Thank you for your contribution.
Kindly update your branch to aid this PR.
However, your code has been added too.
Thanks.

**Review by dohoudaniel — APPROVED** [review]
Kindly update your local branch.

**Comment by NanaAba08** [comment]
Thank you for the response Daniel.
I have updated my branch thank you.

**Pull request closed without merging**
