### PR TITLE
Projects Page

### LINKED ISSUE #40: Project Page
@ekerejosh @coApollo @ValCaite @chisomchinaza @Astro175 @KabzaKole
You have been assigned along with your team lead @masha-a-m to work on the Project Page.
@dohoudaniel will be your moderator.

<strong>Visual Aid</strong>
- <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=26-51&t=lrwFyeZhwBIg7MNw-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=541%3A379&mode=design">Projects Page (Figma)</a>
- <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit?usp=sharing">Website Details</a>
- <a href="https://docs.google.com/document/d/1_qXUmBQZF0VNnnbqzfpFUAMfp7oapNmFq1OTxzSGCxE/edit?usp=sharing">Google Doc (Projects Page)</a>
- <a href="https://youtu.be/Qeibe59f72s">YouTube Video</a>

The "Subscribe to our newsletter" and footer will be implemented by the team working on the Home Page. You don't need to worry about this part.

### PR DESCRIPTION
**Pull request by masha-a-m**
## Description:
The project team implemented the structure of the project page using HTML, and then added styling to it using Vanilla CSS.

## Changes Made:
Two files were created: Projects.html and Projects.css. The projects.html includes the main structure of the project page. It includes four major sections - hero section, the featured projects section which includes images that show the featured projects with text, and a button underneath each image. The second section is the recent projects section which includes images that show the recent projects as well as a text underneath that explains what that project is and a button for each image. The last section is the upcoming section that shows all the upcoming projects, with some text beneath and a button for each image. Also included was some javascript that ensures some functionality of the featured, recent and upcoming sections.

The second file is the projects.css. It includes the styling for the page as a whole, then the styling used for each of the four sections. Lastly, some mediaquery was created to ensure responsiveness of the projects page on smaller to medium devices. 

## Related Issue:
- Fixes #40

### CODE REVIEW

**Comment by MartyOfMCA** [comment]
Hi @masha-a-m, great work from you and your team!

I took a look at the Figma file and noticed some changes.
* The top part of the page has the image centered in the page with some bit of padding away from the viewport

image

But here's your implementation

image

And unfortunately the image gets pushed off the screen when the viewport's width reduces

image

* Some of your buttons appearance gets affected when the viewport's width reduces

image

Thank you!

**Comment by MartyOfMCA** [comment]
Kindly have your team look into implementing something like this to `.hero-section` and its child elements.

image

Great work from your team implementing the changes requested earlier

**Comment by masha-a-m** [comment]
Hello @ALX-SE-Algorithmia/code-reviewing-team 

The project team has implemented the hero section responsive layout

**Review by Algorithmia-SE-2023 — APPROVED** [review]

**Comment by Algorithmia-SE-2023** [comment]
Thank you @masha-a-m @2023rahabu @KabzaKole @khairatAA @MartyOfMCA @dohoudaniel for your hard work.
PR merged.

**Pull request merged**
