### PR TITLE
Events Page

### LINKED ISSUE #42: Event Page
@Adams2004 @oladosuabayomi @TeamKweku @amandawarima @sirsamuelayodele @Arewa01
You have been assigned along with your team lead @samuelogboye to work on the Events Page.
@khairatAA will be your moderator on the team.

**Visual Aid:**
- <a href="https://www.figma.com/proto/dZE0hWhNqcgolmITw5KUKV/Algorithmia-SE-Website?type=design&node-id=68-50&t=O8rGPIFi2zdg1u11-1&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=541%3A379&mode=design">Events Page (Figma)</a>
- <a href="https://docs.google.com/document/d/1GWltuULw7BjHkrT66N243f6Uak5guNJD_N154PZtqvA/edit?usp=sharing">Website Details</a>
- <a href="https://youtu.be/Qeibe59f72s">YouTube Video</a>

Please keep in mind that we are to:
- Implement the structure and the Figma file. The content of the HTML file will be updated soon.

The "Subscribe to our newsletter" and footer will be implemented by the team working on the Home Page. You don't need to worry about this part.

### PR DESCRIPTION
**Pull request by khairatAA**
## Description:
- The purpose of this pull request is the implementation of the front-end (HTML and CSS) of the event page and also a little JS by the event team.

## Changes Made:
- For the event.html: it contains the structure of the event page it also contains a little JavaScript, this is because no file was provided for the JavaScript.

- For the CSS/event.css: it contains all the CSS codes for the design on the event page and also the responsiveness.
## Related Issue:

- Fixes #42

## Screenshots (if applicable):
- all changes can be found in the event.html and css/event.css file.

### CODE REVIEW

**Comment by khairatAA** [comment]
@ALX-SE-Algorithmia/code-reviewing-team please kindly check out the pull request made by the event team. We implemented the html, CSS and JS of the event page of Algorithmia's website. Thank you.

**Comment by khairatAA** [comment]
Hi @ALX-SE-Algorithmia/code-reviewing-team, A new commit has been made, with a few adjustments to the event page. The adjustments made are:
Added a favicon to the event page
Made the navbar scrollable
Changes the background colour of the "join us" button on the navbar to orange and the text to white, then on hover it switches that is the background colour to white and the font colour then becomes orange.
Please kindly review it....
Thanks

**Comment by MartyOfMCA** [comment]
Hello @khairatAA, great work from you and your team.

Kindly take note of the following and do well to fix them:

* Images look a bit stretched.

image
I suggest you use `object-fit` to control that

* `fa-arrow-up` isn't easy to spot.

image
I suggest you ensure it looks just like `fa-circle-chevron-right` (the right arrow in the image)

* The items in the drop-down list for the navigation items have a border-radius. The border-bottom also assigned to `nav-list :hover` and the padding bottom assigned to `nav-list :hover` all damage the experience the user would have when they hover on the nav item with drop-down list.

image
I suggest the following:
1. Removing the line `border-radius`. Found in the rule on line 74 `events.css`
2. Removing `padding-bottom` and border-bottom`. Found in the rule on line 136 `events.css`
3. Should you need more padding on the drop-down items check your rule on line 66 `events.css`. You can adjust the padding there

* I'd would also suggest you maintain your nav-bar like you had earlier. Then use the Intersection Observer API to provide a background color for the nav bar.

Resources:
https://www.smashingmagazine.com/2021/07/dynamic-header-intersection-observer/
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API

**Comment by khairatAA** [comment]
Hy @ALX-SE-Algorithmia/code-reviewing-team, I have updated the event page to meet all the requirements asked. I will list all the updates below:
Changed the favicon
Added intersection observer to the desktop view
Added background color to the navbar 
Made the scroll-up arrow obvious
Made the images object fit-> cover

Kindly review, please

**Comment by MartyOfMCA** [comment]
Great work!

Kindly try adding `transition: all 500ms ease-in-out;` after line 98 to add some smooth transitioning when the intersection observer takes effect.

I also noticed the `scroll-up` looks funny:

image

Lastly, can you guys have a look at the navigation on smaller screens. Perhaps this

image

can be transformed into something like such:

image

I took this just as a sample for your team to have a look at. Thanks!

**Review by dohoudaniel — APPROVED** [review]

**Comment by Algorithmia-SE-2023** [comment]
Our deep appreciation to the Events page team:
@khairatAA @samuelogboye @oladosuabayomi @Adams2004 for their hard work in the implementation of the Events page.
You have all done so well.
PR merged.

**Pull request merged**
